"""add_status_and_error_to_analysis

Revision ID: e510c587332a
Revises: e7850e99b0ef
Create Date: 2025-12-06 22:15:55.073102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e510c587332a'
down_revision: Union[str, Sequence[str], None] = 'e7850e99b0ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analyses', sa.Column('status', sa.String(length=20), server_default='PENDING', nullable=False))
    op.add_column('analyses', sa.Column('error', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analyses', 'error')
    op.drop_column('analyses', 'status')
    # ### end Alembic commands ###
